// scripts/seedDummyUsers.js
// Run with: node scripts/seedDummyUsers.js

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// Same password for all test users
const DEFAULT_PASSWORD = '12345678';

// 60 dummy users: 30 female, 30 male (all USA)
// NOTE: we will auto-generate emails from gender + index
const dummyUsers = [
  // ---------- FEMALES ----------
  {
    first_name: 'Emma',
    last_name: 'Walker',
    gender: 'female',
    dob: '1998-04-12',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Nurse',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Compassionate and family-focused.',
  },
  {
    first_name: 'Olivia',
    last_name: 'Brown',
    gender: 'female',
    dob: '1997-11-05',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Software Engineer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Seeking a sincere and kind partner.',
  },
  {
    first_name: 'Sophia',
    last_name: 'Johnson',
    gender: 'female',
    dob: '1995-02-14',
    city: 'Houston',
    state: 'TX',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Teacher',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Calm and down-to-earth personality.',
  },
  {
    first_name: 'Isabella',
    last_name: 'Davis',
    gender: 'female',
    dob: '1999-07-20',
    city: 'Seattle',
    state: 'WA',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Graphic Designer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Creative, honest and caring.',
  },
  {
    first_name: 'Mia',
    last_name: 'Martinez',
    gender: 'female',
    dob: '1996-09-01',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Doctor',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Focused on deen and strong values.',
  },
  {
    first_name: 'Amelia',
    last_name: 'Clark',
    gender: 'female',
    dob: '1994-05-03',
    city: 'Miami',
    state: 'FL',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Marketing Specialist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Positive mindset and loyal.',
  },
  {
    first_name: 'Charlotte',
    last_name: 'Lopez',
    gender: 'female',
    dob: '1998-03-17',
    city: 'Denver',
    state: 'CO',
    country: 'USA',
    marital_status: 'single',
    education: 'Intermediate',
    occupation: 'Artist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Loves creativity and meaningful conversations.',
  },
  {
    first_name: 'Harper',
    last_name: 'Hill',
    gender: 'female',
    dob: '2000-01-22',
    city: 'Phoenix',
    state: 'AZ',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Student',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Easy-going and sincere personality.',
  },
  {
    first_name: 'Evelyn',
    last_name: 'Green',
    gender: 'female',
    dob: '1993-06-19',
    city: 'Dallas',
    state: 'TX',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Lawyer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Ambitious yet humble.',
  },
  {
    first_name: 'Abigail',
    last_name: 'Adams',
    gender: 'female',
    dob: '1997-12-11',
    city: 'San Diego',
    state: 'CA',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Photographer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Loves nature and meaningful bonds.',
  },
  {
    first_name: 'Ella',
    last_name: 'Perez',
    gender: 'female',
    dob: '1998-08-10',
    city: 'Austin',
    state: 'TX',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Medical Assistant',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Friendly and open-minded.',
  },
  {
    first_name: 'Aria',
    last_name: 'Bennett',
    gender: 'female',
    dob: '1994-09-15',
    city: 'Atlanta',
    state: 'GA',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Business Analyst',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Values honesty and trust.',
  },
  {
    first_name: 'Scarlett',
    last_name: 'Rivera',
    gender: 'female',
    dob: '1995-03-03',
    city: 'Orlando',
    state: 'FL',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Writer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Introverted, thoughtful and caring.',
  },
  {
    first_name: 'Victoria',
    last_name: 'Thompson',
    gender: 'female',
    dob: '1996-10-18',
    city: 'Charlotte',
    state: 'NC',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Chef',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Loves cooking and family gatherings.',
  },
  {
    first_name: 'Madison',
    last_name: 'Lee',
    gender: 'female',
    dob: '1998-05-30',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Biologist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Kind-hearted and soft-spoken.',
  },
  {
    first_name: 'Lily',
    last_name: 'Allen',
    gender: 'female',
    dob: '1999-02-27',
    city: 'Nashville',
    state: 'TN',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'UX Designer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Thoughtful and creative.',
  },
  {
    first_name: 'Hannah',
    last_name: 'Young',
    gender: 'female',
    dob: '1997-04-11',
    city: 'Tampa',
    state: 'FL',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'HR Specialist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Empathetic and supportive.',
  },
  {
    first_name: 'Zoey',
    last_name: 'Baker',
    gender: 'female',
    dob: '1996-07-24',
    city: 'Cleveland',
    state: 'OH',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Accountant',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Organized and sincere.',
  },
  {
    first_name: 'Nora',
    last_name: 'Carter',
    gender: 'female',
    dob: '1995-11-09',
    city: 'Detroit',
    state: 'MI',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Researcher',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Dedicated and focused.',
  },
  {
    first_name: 'Grace',
    last_name: 'Mitchell',
    gender: 'female',
    dob: '1998-01-17',
    city: 'Cincinnati',
    state: 'OH',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Dental Assistant',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Warm personality and kind.',
  },
  {
    first_name: 'Riley',
    last_name: 'Gonzalez',
    gender: 'female',
    dob: '1999-06-26',
    city: 'Kansas City',
    state: 'MO',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Student',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Friendly and positive.',
  },
  {
    first_name: 'Hazel',
    last_name: 'Ward',
    gender: 'female',
    dob: '1994-07-12',
    city: 'Portland',
    state: 'OR',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Therapist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Loves emotional intelligence and growth.',
  },
  {
    first_name: 'Violet',
    last_name: 'Torres',
    gender: 'female',
    dob: '1997-09-22',
    city: 'Minneapolis',
    state: 'MN',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Nurse',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Calm and friendly.',
  },
  {
    first_name: 'Aurora',
    last_name: 'Hughes',
    gender: 'female',
    dob: '1998-03-08',
    city: 'Indianapolis',
    state: 'IN',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Receptionist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Very approachable and sweet.',
  },
  {
    first_name: 'Penelope',
    last_name: 'Flores',
    gender: 'female',
    dob: '1996-06-17',
    city: 'Raleigh',
    state: 'NC',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Scientist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Curious mind and calm nature.',
  },
  {
    first_name: 'Layla',
    last_name: 'Simmons',
    gender: 'female',
    dob: '1995-02-07',
    city: 'Salt Lake City',
    state: 'UT',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Admin Assistant',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Detail-oriented and caring.',
  },
  {
    first_name: 'Stella',
    last_name: 'Foster',
    gender: 'female',
    dob: '1997-04-28',
    city: 'San Jose',
    state: 'CA',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Consultant',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Independent and kind-hearted.',
  },
  {
    first_name: 'Hannah',
    last_name: 'Murphy',
    gender: 'female',
    dob: '1998-10-16',
    city: 'Columbus',
    state: 'OH',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Teacher',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Patient and friendly.',
  },
  {
    first_name: 'Sofia',
    last_name: 'Kim',
    gender: 'female',
    dob: '1996-01-30',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Engineer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Goal-oriented and calm.',
  },
  {
    first_name: 'Ellie',
    last_name: 'Gibson',
    gender: 'female',
    dob: '1995-05-21',
    city: 'Las Vegas',
    state: 'NV',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Sales Associate',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Loves helping others.',
  },

  // ---------- MALES ----------
  {
    first_name: 'Ahmed',
    last_name: 'Khan',
    gender: 'male',
    dob: '1992-03-10',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Software Engineer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Engineer who values deen and family.',
  },
  {
    first_name: 'Bilal',
    last_name: 'Malik',
    gender: 'male',
    dob: '1993-07-18',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Accountant',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Calm, responsible and family-oriented.',
  },
  {
    first_name: 'Omar',
    last_name: 'Ali',
    gender: 'male',
    dob: '1991-12-02',
    city: 'Houston',
    state: 'TX',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Data Analyst',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Enjoys learning and good conversation.',
  },
  {
    first_name: 'Yusuf',
    last_name: 'Siddiqi',
    gender: 'male',
    dob: '1994-09-25',
    city: 'Dallas',
    state: 'TX',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Mechanical Engineer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Hard-working and sincere.',
  },
  {
    first_name: 'Musa',
    last_name: 'Farid',
    gender: 'male',
    dob: '1990-05-14',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Doctor',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Values honesty and responsibility.',
  },
  {
    first_name: 'Hamza',
    last_name: 'Qureshi',
    gender: 'male',
    dob: '1995-01-09',
    city: 'Seattle',
    state: 'WA',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'UX Designer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Creative mind with a simple lifestyle.',
  },
  {
    first_name: 'Ali',
    last_name: 'Raza',
    gender: 'male',
    dob: '1993-11-29',
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Product Manager',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Focused on growth and balance.',
  },
  {
    first_name: 'Zaid',
    last_name: 'Mirza',
    gender: 'male',
    dob: '1992-06-04',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Marketing Specialist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Honest, caring and social.',
  },
  {
    first_name: 'Ibrahim',
    last_name: 'Aziz',
    gender: 'male',
    dob: '1994-02-21',
    city: 'Miami',
    state: 'FL',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Civil Engineer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Enjoys community work and family time.',
  },
  {
    first_name: 'Khalid',
    last_name: 'Hassan',
    gender: 'male',
    dob: '1996-08-15',
    city: 'Atlanta',
    state: 'GA',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Teacher',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Patient and respectful personality.',
  },
  {
    first_name: 'Hassan',
    last_name: 'Syed',
    gender: 'male',
    dob: '1991-07-07',
    city: 'Orlando',
    state: 'FL',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Researcher',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Calm and analytical mindset.',
  },
  {
    first_name: 'Usman',
    last_name: 'Iqbal',
    gender: 'male',
    dob: '1993-03-19',
    city: 'Houston',
    state: 'TX',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Business Analyst',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Enjoys a balanced and simple life.',
  },
  {
    first_name: 'Ismail',
    last_name: 'Sheikh',
    gender: 'male',
    dob: '1992-10-02',
    city: 'Phoenix',
    state: 'AZ',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Consultant',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Good listener and thoughtful.',
  },
  {
    first_name: 'Faris',
    last_name: 'Anwar',
    gender: 'male',
    dob: '1995-12-25',
    city: 'Denver',
    state: 'CO',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Sales Manager',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Outgoing, but grounded in values.',
  },
  {
    first_name: 'Salman',
    last_name: 'Rauf',
    gender: 'male',
    dob: '1990-04-30',
    city: 'Seattle',
    state: 'WA',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Doctor',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Dedicated to work and family.',
  },
  {
    first_name: 'Tariq',
    last_name: 'Nasir',
    gender: 'male',
    dob: '1994-09-11',
    city: 'San Diego',
    state: 'CA',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Graphic Designer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Creative and respectful.',
  },
  {
    first_name: 'Rayyan',
    last_name: 'Khalil',
    gender: 'male',
    dob: '1993-11-01',
    city: 'Austin',
    state: 'TX',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Software Engineer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Introvert with a kind heart.',
  },
  {
    first_name: 'Danial',
    last_name: 'Hameed',
    gender: 'male',
    dob: '1992-06-08',
    city: 'Tampa',
    state: 'FL',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Accountant',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Responsible and organized.',
  },
  {
    first_name: 'Jawad',
    last_name: 'Shah',
    gender: 'male',
    dob: '1995-03-27',
    city: 'Cleveland',
    state: 'OH',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Research Scientist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Curious and humble.',
  },
  {
    first_name: 'Salim',
    last_name: 'Hadi',
    gender: 'male',
    dob: '1991-02-19',
    city: 'Detroit',
    state: 'MI',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Technician',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Hands-on and down to earth.',
  },
  {
    first_name: 'Zaheer',
    last_name: 'Mahmood',
    gender: 'male',
    dob: '1994-10-13',
    city: 'Cincinnati',
    state: 'OH',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Project Manager',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Organized, considerate and calm.',
  },
  {
    first_name: 'Adil',
    last_name: 'Faruqi',
    gender: 'male',
    dob: '1992-01-05',
    city: 'Kansas City',
    state: 'MO',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Business Owner',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Entrepreneur with balanced priorities.',
  },
  {
    first_name: 'Ameer',
    last_name: 'Zahid',
    gender: 'male',
    dob: '1993-08-23',
    city: 'Portland',
    state: 'OR',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Therapist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Empathetic and grounded.',
  },
  {
    first_name: 'Sami',
    last_name: 'Latif',
    gender: 'male',
    dob: '1994-04-16',
    city: 'Minneapolis',
    state: 'MN',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Nurse',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Gentle and kind personality.',
  },
  {
    first_name: 'Faizan',
    last_name: 'Chaudhry',
    gender: 'male',
    dob: '1995-09-09',
    city: 'Indianapolis',
    state: 'IN',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Engineer',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Ambitious but grounded.',
  },
  {
    first_name: 'Imran',
    last_name: 'Khalid',
    gender: 'male',
    dob: '1991-05-28',
    city: 'Raleigh',
    state: 'NC',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Admin Assistant',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Helpful and considerate.',
  },
  {
    first_name: 'Nadeem',
    last_name: 'Saleem',
    gender: 'male',
    dob: '1993-02-14',
    city: 'Salt Lake City',
    state: 'UT',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Consultant',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Logical thinker with soft nature.',
  },
  {
    first_name: 'Yasir',
    last_name: 'Rashid',
    gender: 'male',
    dob: '1992-11-30',
    city: 'San Jose',
    state: 'CA',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Technologist',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Tech-savvy and friendly.',
  },
  {
    first_name: 'Atif',
    last_name: 'Saeed',
    gender: 'male',
    dob: '1994-07-03',
    city: 'Columbus',
    state: 'OH',
    country: 'USA',
    marital_status: 'single',
    education: 'Masters',
    occupation: 'Teacher',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Patient and helpful.',
  },
  {
    first_name: 'Farhan',
    last_name: 'Naveed',
    gender: 'male',
    dob: '1995-10-19',
    city: 'Las Vegas',
    state: 'NV',
    country: 'USA',
    marital_status: 'single',
    education: 'Bachelors',
    occupation: 'Sales Associate',
    practice_level: 'practicing',
    denomination: 'Sunni',
    has_children: false,
    bio: 'Sociable and caring.',
  },
];

async function main() {
  console.log(`Seeding ${dummyUsers.length} users...`);

  let femaleCount = 0;
  let maleCount = 0;

  for (const u of dummyUsers) {
    // Generate easy-to-remember email based on gender + index
    let email;
    if (u.gender === 'female') {
      femaleCount += 1;
      email = `girl${femaleCount}@gmail.com`;
    } else {
      maleCount += 1;
      email = `boy${maleCount}@gmail.com`;
    }

    console.log(`\nCreating auth user for ${email} ...`);

    // 1) Create auth user
    const { data: authData, error: authError } = await supabase.auth.admin.createUser({
      email,
      password: DEFAULT_PASSWORD,
      email_confirm: true,
      user_metadata: {
        first_name: u.first_name,
        last_name: u.last_name,
        gender: u.gender,
      },
    });

    if (authError) {
      console.error(`  ❌ Auth error for ${email}:`, authError.message);
      continue;
    }

    const authUser = authData.user;
    if (!authUser) {
      console.error(`  ❌ No auth user returned for ${email}`);
      continue;
    }

    console.log(`  ✅ Auth user created with id: ${authUser.id}`);

    // 2) Insert profile row with same id
    const { error: profileError } = await supabase.from('profiles').insert({
      id: authUser.id,
      email,
      first_name: u.first_name,
      last_name: u.last_name,
      gender: u.gender,
      dob: u.dob,
      city: u.city,
      state: u.state,
      country: u.country,
      marital_status: u.marital_status,
      education: u.education,
      occupation: u.occupation,
      practice_level: u.practice_level,
      denomination: u.denomination,
      has_children: u.has_children,
      bio: u.bio,
      onboarding_completed: true,
      subscription_tier: 'free',
      subscription_status: 'inactive',
      email_verified: true,
      email_verified_at: new Date().toISOString(),
      is_test_user: true,
    });

    if (profileError) {
      console.error(`  ❌ Profile insert error for ${email}:`, profileError.message);
    } else {
      console.log(`  ✅ Profile created for ${email}`);
    }
  }

  console.log('\nDone seeding dummy users.');
}

main().catch((err) => {
  console.error('Unexpected error in seed script:', err);
  process.exit(1);
});
